apiVersion: apps/v1
kind: Deployment
metadata:
  name: ernest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ernest-api
  template:
    metadata:
      labels:
        app: ernest-api
    spec:
      containers:
        - name: ernest-api
          image: us-docker.pkg.dev/rock-module-403103/ernest-api/api-tests
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "250m"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10
